const DashboardActionTypes = {
  FETCH_DASHBOARD_ITEMS_START: 'FETCH_DASHBOARD_ITEMS_START',
  FETCH_DASHBOARD_ITEMS_SUCCESS: 'FETCH_DASHBOARD_ITEMS_SUCCESS',
  FETCH_DASHBOARD_ITEMS_FAILURE: 'FETCH_DASHBOARD_ITEMS_FAILURE',

  FETCH_ACCOUNT_TYPE_ITEMS_START: 'FETCH_ACCOUNT_TYPE_ITEMS_START',
  FETCH_ACCOUNT_TYPE_ITEMS_SUCCESS: 'FETCH_ACCOUNT_TYPE_ITEMS_SUCCESS',
  FETCH_ACCOUNT_TYPE_ITEMS_FAILURE: 'FETCH_ACCOUNT_TYPE_ITEMS_FAILURE'
}
export default DashboardActionTypes
