const DraftsActionTypes = {
  // Fetching Items
  FETCH_DRAFTS_ITEMS_START: 'FETCH_DRAFTS_ITEMS_START',
  FETCH_DRAFTS_ITEMS_SUCCESS: 'FETCH_DRAFTS_ITEMS_SUCCESS',
  FETCH_DRAFTS_ITEMS_FAILURE: 'FETCH_DRAFTS_ITEMS_FAILURE',

  // Fetching metadata
  FETCH_DRAFTS_METADATA_START: 'FETCH_DRAFTS_METADATA_START',
  FETCH_DRAFTS_METADATA_SUCCESS: 'FETCH_DRAFTS_METADATA_SUCCESS',
  FETCH_DRAFTS_METADATA_FAILURE: 'FETCH_DRAFTS_METADATA_FAILURE',

  DRAFTS_SHOW_SMALL_LOADER: 'DRAFTS_SHOW_SMALL_LOADER',
  DRAFTS_SHOW_BIG_LOADER: 'DRAFTS_SHOW_BIG_LOADER',

  DRAFTS_PAGESIZE: 'DRAFTS_PAGESIZE',
  DRAFTS_PAGE_NUMBER: 'DRAFTS_PAGE_NUMBER',

  FETCH_IS_GOING_FORWARD_FLAG: 'FETCH_IS_GOING_FORWARD_FLAG',
  UPDATE_IS_GOING_FORWARD_FLAG: 'UPDATE_IS_GOING_FORWARD_FLAG',
  FETCH_PAGINARION_KEYS: 'FETCH_PAGINARION_KEYS',
  UPDATE_PAGINATION_KEYS: 'UPDATE_PAGINATION_KEYS',
  UPDATE_SEARCH_AFTER_KEYS: 'UPDATE_SEARCH_AFTER_KEYS',
  FETCH_DRAFT_SEARCH_START: 'FETCH_DRAFT_SEARCH_START',

  FETCH_DRAFTS_SORT_START: 'FETCH_DRAFTS_SORT_START',
  FETCH_DRAFTS_SORT_SUCCESS: 'FETCH_DRAFTS_SORT_SUCCESS',
  FETCH_DRAFTS_SORT_FAILURE: 'FETCH_DRAFTS_SORT_FAILURE',
  UPDATE_DRAFTS_SORT_INFO: 'UPDATE_DRAFTS_SORT_INFO',
  UPDATE_DRAFTS_ITEMS: 'UPDATE_DRAFTS_ITEMS'
}
export default DraftsActionTypes
