const MyAccessActionTypes = {
  SHOW_SMALL_ACCESS_LOADER: 'SHOW_SMALL_ACCESS_LOADER',
  SHOW_BIG_ACCESS_LOADER: 'SHOW_BIG_ACCESS_LOADER',

  UPDATE_ACCESS_IS_GOING_FORWARD_FLAG: 'UPDATE_ACCESS_IS_GOING_FORWARD_FLAG',
  UPDATE_ACCESS_PAGINATION_KEYS: 'UPDATE_ACCESS_PAGINATION_KEYS',

  ACCESS_PAGE_SIZE: 'ACCESS_PAGE_SIZE',
  ACCESS_PAGE_NUMBER: 'ACCESS_PAGE_NUMBER',

  // Fetching -group asset metadata
  FETCH_GROUP_ACCESS_METADATA_START: 'FETCH_GROUP_ACCESS_METADATA_START',
  FETCH_GROUP_ACCESS_METADATA_SUCCESS: 'FETCH_GROUP_ACCESS_METADATA_SUCCESS',
  FETCH_GROUP_ACCESS_METADATA_FAILURE: 'FETCH_GROUP_ACCESS_METADATA_FAILURE',

  // Fetching Items
  FETCH_GROUP_ACCESS_ITEMS_START: 'FETCH_GROUP_ACCESS_ITEMS_START',
  FETCH_GROUP_ACCESS_ITEMS_SUCCESS: 'FETCH_GROUP_ACCESS_ITEMS_SUCCESS',
  FETCH_GROUP_ACCESS_ITEMS_FAILURE: 'FETCH_GROUP_ACCESS_ITEMS_FAILURE',

  FETCH_GROUP_ACCESS_SORT_START: 'FETCH_GROUP_ACCESS_SORT_START',
  UPDATE_GROUP_ACCESS_SORT_INFO: 'UPDATE_GROUP_ACCESS_SORT_INFO',

  FETCH_GROUP_ACCESS_SEARCH_START: 'FETCH_GROUP_ACCESS_SEARCH_START'
}
export default MyAccessActionTypes
