const ApprovalsActionTypes = {
  // Fetching Items
  FETCH_APPROVALS_ITEMS_START: 'FETCH_APPROVALS_ITEMS_START',
  FETCH_APPROVALS_ITEMS_SUCCESS: 'FETCH_APPROVALS_ITEMS_SUCCESS',
  FETCH_APPROVALS_ITEMS_FAILURE: 'FETCH_APPROVALS_ITEMS_FAILURE',
  UPDATE_APPROVALS_ITEMS: 'UPDATE_APPROVALS_ITEMS',

  // Fetching personal asset metadata
  FETCH_APPROVALS_METADATA_START: 'FETCH_APPROVALS_METADATA_START',
  FETCH_APPROVALS_METADATA_SUCCESS: 'FETCH_APPROVALS_METADATA_SUCCESS',
  FETCH_APPROVALS_METADATA_FAILURE: 'FETCH_APPROVALS_METADATA_FAILURE',

  // Notification message located above the table
  UPDATE_APPROVALS_NOTIFICATION_MESSAGE: 'UPDATE_APPROVALS_NOTIFICATION_MESSAGE',

  SHOW_SMALL_LOADER: 'SHOW_SMALL_LOADER',
  SHOW_BIG_LOADER: 'SHOW_BIG_LOADER',

  APPROVALS_PAGESIZE: 'APPROVALS_PAGESIZE',
  APPROVALS_PAGE_NUMBER: 'APPROVALS_PAGE_NUMBER',

  FETCH_APPROVALS_IS_GOING_FORWARD_FLAG: 'FETCH_APPROVALS_IS_GOING_FORWARD_FLAG',
  UPDATE_APPROVALS_IS_GOING_FORWARD_FLAG: 'UPDATE_APPROVALS_IS_GOING_FORWARD_FLAG',
  FETCH_APPROVALS_PAGINARION_KEYS: 'FETCH_APPROVALS_PAGINARION_KEYS',
  UPDATE_APPROVALS_PAGINATION_KEYS: 'UPDATE_APPROVALS_PAGINATION_KEYS',
  UPDATE_SEARCH_AFTER_KEYS: 'UPDATE_SEARCH_AFTER_KEYS',

  FETCH_APPROVALS_SEARCH_START: 'FETCH_APPROVALS_SEARCH_START',
  FETCH_APPROVALS_SEARCH_SUCCESS: 'FETCH_APPROVALS_SEARCH_SUCCESS',
  FETCH_APPROVALS_SEARCH_FAILURE: 'FETCH_APPROVALS_SEARCH_FAILURE',

  FETCH_APPROVALS_SORT_START: 'FETCH_APPROVALS_SORT_START',
  FETCH_APPROVALS_SORT_SUCCESS: 'FETCH_APPROVALS_SORT_SUCCESS',
  FETCH_APPROVALS_SORT_FAILURE: 'FETCH_APPROVALS_SORT_FAILURE',
  UPDATE_APPROVALS_SORT_INFO: 'UPDATE_APPROVALS_SORT_INFO'
}
export default ApprovalsActionTypes
