const ReviewActionTypes = {
  // Fetching Items
  FETCH_REVIEW_ITEMS_START: 'FETCH_REVIEW_ITEMS_START',
  FETCH_REVIEW_ITEMS_SUCCESS: 'FETCH_REVIEW_ITEMS_SUCCESS',
  FETCH_REVIEW_ITEMS_FAILURE: 'FETCH_REVIEW_ITEMS_FAILURE',
  UPDATE_REVIEW_ITEMS: 'UPDATE_REVIEW_ITEMS',

  // Fetching Items
  FETCH_REVIEW_FILTER_START: 'FETCH_REVIEW_FILTER_START',
  FETCH_REVIEW_FILTER_SUCCESS: 'FETCH_REVIEW_FILTER_SUCCESS',
  FETCH_REVIEW_FILTER_FAILURE: 'FETCH_REVIEW_FILTER_FAILURE',

  // Search Items
  FETCH_REVIEW_SEARCH_START: 'FETCH_REVIEW_SEARCH_START',
  FETCH_REVIEW_SEARCH_SUCCESS: 'FETCH_REVIEW_SEARCH_SUCCESS',
  FETCH_REVIEW_SEARCH_FAILURE: 'FETCH_REVIEW_SEARCH_FAILURE',

  // Notification message located above the table
  UPDATE_REVIEW_NOTIFICATION_MESSAGE: 'UPDATE_REVIEW_NOTIFICATION_MESSAGE',

  // Fetching metadata
  FETCH_REVIEW_METADATA_START: 'FETCH_REVIEW_METADATA_START',
  FETCH_REVIEW_METADATA_SUCCESS: 'FETCH_REVIEW_METADATA_SUCCESS',
  FETCH_REVIEW_METADATA_FAILURE: 'FETCH_REVIEW_METADATA_FAILURE',
  // Reviewer Data
  FETCH_REVIEWER_DATA_START: 'FETCH_REVIEWER_DATA_START',
  FETCH_REVIEWER_DATA_SUCCESS: 'FETCH_REVIEWER_DATA_SUCCESS',
  FETCH_REVIEWER_DATA_FAILURE: 'FETCH_REVIEWER_DATA_FAILURE',
  // Monitor Data
  FETCH_MONITOR_DATA_START: 'FETCH_MONITOR_DATA_START',
  FETCH_MONITOR_DATA_SUCCESS: 'FETCH_MONITOR_DATA_SUCCESS',
  FETCH_MONITOR_DATA_FAILURE: 'FETCH_MONITOR_DATA_FAILURE',

  // Sign off items based the general actions ( e.g. maintain, revoke, allow exceptions )
  SIGN_OFF_ITEMS: 'SIGN_OFF_ITEMS',
  APPLY_FILTER: 'APPLY_FILTER',

  REVIEW_TYPE: 'REVIEW_TYPE',

  REVIEW_PAGESIZE: 'REVIEW_PAGESIZE',
  REVIEW_PAGE_NUMBER: 'REVIEW_PAGE_NUMBER',

  SHOW_SMALL_LOADER: 'SHOW_SMALL_LOADER',
  SHOW_BIG_LOADER: 'SHOW_BIG_LOADER',
  SHOW_SAMLL_LOADER: 'SHOW_SAMLL_LOADER',

  REVIEW_TOTAL_ITEM_COUNT: 'REVIEW_TOTAL_ITEM_COUNT',
  REVIEW_GROUP_PAGESIZE: 'REVIEW_GROUP_PAGESIZE',
  REVIEW_GROUP_PAGE_NUMBER: 'REVIEW_GROUP_PAGE_NUMBER',
  REVIEW_FILTER_DATA: 'REVIEW_FILTER_DATA',

  // Fetching Items
  FETCH_REVIEW_SORT_START: 'FETCH_REVIEW_SORT_START',
  FETCH_REVIEW_SORT_SUCCESS: 'FETCH_REVIEW_SORT_SUCCESS',
  FETCH_REVIEW_SORT_FAILURE: 'FETCH_REVIEW_SORT_FAILURE',
  UPDATE_SORT_INFO: 'UPDATE_SORT_INFO',
  FETCH_REVIEWER_SORT_START: 'FETCH_REVIEWER_SORT_START',
  FETCH_MONITOR_SORT_START: 'FETCH_MONITOR_SORT_START',

  FETCH_IS_GOING_FORWARD_FLAG: 'FETCH_IS_GOING_FORWARD_FLAG',
  UPDATE_IS_GOING_FORWARD_FLAG: 'UPDATE_IS_GOING_FORWARD_FLAG',
  FETCH_PAGINARION_KEYS: 'FETCH_PAGINARION_KEYS',
  UPDATE_PAGINATION_KEYS: 'UPDATE_PAGINATION_KEYS',

  UPDATE_EXPAND_INDEX: 'UPDATE_EXPAND_INDEX',
  UPDATE_SEARCH_KEY: 'UPDATE_SEARCH_KEY',
  UPDATE_GROUPBY_KEY: 'UPDATE_GROUPBY_KEY',
  UPDATE_SEARCH_AFTER_KEY: 'UPDATE_SEARCH_AFTER_KEY',
  UPDATE_IS_MONITOR: 'UPDATE_IS_MONITOR',
  UPDATE_IS_REVIEWER_TAB_ACTIVE: 'UPDATE_IS_REVIEWER_TAB_ACTIVE',
  UPDATE_REVIEWER_DATA_LOADED: 'UPDATE_REVIEWER_DATA_LOADED',
  UPDATE_MONITOR_DATA_LOADED: 'UPDATE_MONITOR_DATA_LOADED',

  UPDATE_CERTIFICATION: 'UPDATE_CERTIFICATION',

  UPDATE_SELECTED_REVIEW_ITEMS: 'UPDATE_SELECTED_REVIEW_ITEMS',

  SET_GROUPED_ITEMS_SEARCH_FLAG: 'SET_GROUPED_ITEMS_SEARCH_FLAG',

  FETCH_GROUP_BY_REVIEWER_SEARCH_START: 'FETCH_GROUP_BY_REVIEWER_SEARCH_START',

  FETCH_REVIEW_GROUPBY_START: 'FETCH_REVIEW_GROUPBY_START',

  SET_PAGE_COUNT: 'SET_PAGE_COUNT',
  SET_NORMALIZED_MONITOR_DATA: 'SET_NORMALIZED_MONITOR_DATA',

  // TO CHECK IF A CAMPAIGN IS SEMI ANNUAL OR NOT
  FETCH_IS_SEMIANNUAL_CAMPAIGN: 'FETCH_IS_SEMIANNUAL_CAMPAIGN',
  UPDATE_IS_SEMIANNUAL_CAMPAIGN: 'UPDATE_IS_SEMIANNUAL_CAMPAIGN',

  FETCH_GROUP_MONITOR_PAGE_SIZE_ROWS_CHANGE_HANDLER:
    'FETCH_GROUP_MONITOR_PAGE_SIZE_ROWS_CHANGE_HANDLER',
  UPDATE_MONITOR_GROUP_PAGE_SIZE_ROWS_CHANGE_HANDLER:
    'UPDATE_MONITOR_GROUP_PAGE_SIZE_ROWS_CHANGE_HANDLER',

  FETCH_REVIEWER__GROUPBY_SORT_START: 'FETCH_REVIEWER__GROUPBY_SORT_START'
}
export default ReviewActionTypes
