const JustificationsActionTypes = {
  // Fetching Items
  FETCH_JUSTIFICATIONS_ITEMS_START: 'FETCH_JUSTIFICATIONS_ITEMS_START',
  FETCH_JUSTIFICATIONS_ITEMS_SUCCESS: 'FETCH_JUSTIFICATIONS_ITEMS_SUCCESS',
  FETCH_JUSTIFICATIONS_ITEMS_FAILURE: 'FETCH_JUSTIFICATIONS_ITEMS_FAILURE',

  // Fetching personal asset metadata
  FETCH_JUSTIFICATIONS_METADATA_START: 'FETCH_JUSTIFICATIONS_METADATA_START',
  FETCH_JUSTIFICATIONS_METADATA_SUCCESS: 'FETCH_JUSTIFICATIONS_METADATA_SUCCESS',
  FETCH_JUSTIFICATIONS_METADATA_FAILURE: 'FETCH_JUSTIFICATIONS_METADATA_FAILURE',

  SHOW_SMALL_LOADER: 'SHOW_SMALL_LOADER',
  SHOW_BIG_LOADER: 'SHOW_BIG_LOADER',

  UPDATE_JUSTIFICATIONS_IS_GOING_FORWARD_FLAG: 'UPDATE_JUSTIFICATIONS_IS_GOING_FORWARD_FLAG',
  UPDATE_JUSTIFICATIONS_PAGINATION_KEYS: 'UPDATE_JUSTIFICATIONS_PAGINATION_KEYS',

  JUSTIFICATIONS_PAGESIZE: 'JUSTIFICATIONS_PAGESIZE',
  JUSTIFICATIONS_PAGE_NUMBER: 'JUSTIFICATIONS_PAGE_NUMBER',

  FETCH_JUSTIFICATIONS_SORT_START: 'FETCH_JUSTIFICATIONS_SORT_START',
  FETCH_JUSTIFICATIONS_SORT_SUCCESS: 'FETCH_JUSTIFICATIONS_SORT_SUCCESS',
  FETCH_JUSTIFICATIONS_SORT_FAILURE: 'FETCH_JUSTIFICATIONS_SORT_FAILURE',
  UPDATE_JUSTIFICATIONS_SORT_INFO: 'UPDATE_JUSTIFICATIONS_SORT_INFO',

  FETCH_JUSTIFICATIONS_SEARCH_START: 'FETCH_JUSTIFICATIONS_SEARCH_START'
}
export default JustificationsActionTypes
