const ReviewsActionTypes = {
  FETCH_REVIEWS_ITEMS_START: 'FETCH_REVIEWS_ITEMS_START',
  FETCH_REVIEWS_ITEMS_SUCCESS: 'FETCH_REVIEWS_ITEMS_SUCCESS',
  FETCH_REVIEWS_ITEMS_FAILURE: 'FETCH_REVIEWS_ITEMS_FAILURE',

  FETCH_REVIEWS_METADATA_START: 'FETCH_REVIEWS_METADATA_START',
  FETCH_REVIEWS_METADATA_SUCCESS: 'FETCH_REVIEWS_METADATA_SUCCESS',
  FETCH_REVIEWS_METADATA_FAILURE: 'FETCH_REVIEWS_METADATA_FAILURE',

  FETCH_REVIEWS_SEARCH_START: 'FETCH_REVIEWS_SEARCH_START',
  FETCH_REVIEWS_SEARCH_SUCCESS: 'FETCH_REVIEWS_SEARCH_SUCCESS',
  FETCH_REVIEWS_SEARCH_FAILURE: 'FETCH_REVIEWS_SEARCH_FAILURE',

  FETCH_REVIEWS_SORT_START: 'FETCH_REVIEWS_SORT_START',
  FETCH_REVIEWS_SORT_SUCCESS: 'FETCH_REVIEWS_SORT_SUCCESS',
  FETCH_REVIEWS_SORT_FAILURE: 'FETCH_REVIEWS_SORT_FAILURE',
  UPDATE_SORT_DATA: 'UPDATE_SORT_DATA',

  SHOW_SMALL_LOADER: 'SHOW_SMALL_LOADER',

  REVIEWS_PAGESIZE: 'REVIEWS_PAGESIZE',
  REVIEWS_PAGE_NUMBER: 'REVIEWS_PAGE_NUMBER'
}
export default ReviewsActionTypes
