const MyTeamActionTypes = {
  FETCH_MYTEAM_ITEMS_START: 'FETCH_MYTEAM_ITEMS_START',
  FETCH_MYTEAM_ITEMS_SUCCESS: 'FETCH_MYTEAM_ITEMS_SUCCESS',
  FETCH_MYTEAM_ITEMS_FAILURE: 'FETCH_MYTEAM_ITEMS_FAILURE',

  FETCH_MYTEAM_METADATA_START: 'FETCH_MYTEAM_METADATA_START',
  FETCH_MYTEAM_METADATA_SUCCESS: 'FETCH_MYTEAM_METADATA_SUCCESS',
  FETCH_MYTEAM_METADATA_FAILURE: 'FETCH_MYTEAM_METADATA_FAILURE',

  FETCH_MYTEAM_SEARCH_START: 'FETCH_MYTEAM_SEARCH_START',
  FETCH_MYTEAM_SEARCH_SUCCESS: 'FETCH_MYTEAM_SEARCH_SUCCESS',
  FETCH_MYTEAM_SEARCH_FAILURE: 'FETCH_MYTEAM_SEARCH_FAILURE',

  MYTEAM_PAGESIZE: 'MYTEAM_PAGESIZE',
  MYTEAM_PAGE_NUMBER: 'MYTEAM_PAGE_NUMBER',

  SHOW_BIG_LOADER: 'SHOW_BIG_LOADER',

  FETCH_IS_GOING_FORWARD_FLAG: 'FETCH_IS_GOING_FORWARD_FLAG',
  UPDATE_IS_GOING_FORWARD_FLAG: 'UPDATE_IS_GOING_FORWARD_FLAG',
  FETCH_PAGINARION_KEYS: 'FETCH_PAGINARION_KEYS',
  UPDATE_PAGINATION_KEYS: 'UPDATE_PAGINATION_KEYS',

  FETCH_MYTEAM_SORT_START: 'FETCH_MYTEAM_SORT_START',
  FETCH_MYTEAM_SORT_SUCCESS: 'FETCH_MYTEAM_SORT_SUCCESS',
  FETCH_MYTEAM_SORT_FAILURE: 'FETCH_MYTEAM_SORT_FAILURE',
  UPDATE_MYTEAM_SORT_INFO: 'UPDATE_MYTEAM_SORT_INFO'
}
export default MyTeamActionTypes
