const ProfileActionTypes = {
  FETCH_PROFILE_START: 'FETCH_PROFILE_START',
  FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',

  FETCH_PROFILE_DETAILS_START: 'FETCH_PROFILE_DETAILS_START',
  FETCH_PROFILE_DETAILS_SUCCESS: 'FETCH_PROFILE_DETAILS_SUCCESS',
  FETCH_PROFILE_DETAILS_FAILURE: 'FETCH_PROFILE_DETAILS_FAILURE',

  FETCH_PROVISIONING_ROLES_SUCCESS: 'FETCH_PROVISIONING_ROLES_SUCCESS',
  FETCH_PROVISIONING_ROLES_FAILURE: 'FETCH_PROVISIONING_ROLES_FAILURE',
  FETCH_PROFILE_ROLE: 'FETCH_PROFILE_ROLE'
}
export default ProfileActionTypes
