const ServiceDeskAdminActionTypes = {
  FETCH_SERVICEDESKADMIN_ITEMS_START: 'FETCH_SERVICEDESKADMIN_ITEMS_START',
  FETCH_SERVICEDESKADMIN_ITEMS_SUCCESS: 'FETCH_SERVICEDESKADMIN_ITEMS_SUCCESS',
  FETCH_SERVICEDESKADMIN_ITEMS_FAILURE: 'FETCH_SERVICEDESKADMIN_ITEMS_FAILURE',

  FETCH_SERVICEDESKADMIN_METADATA_START: 'FETCH_SERVICEDESKADMIN_METADATA_START',
  FETCH_SERVICEDESKADMIN_METADATA_SUCCESS: 'FETCH_SERVICEDESKADMIN_METADATA_SUCCESS',
  FETCH_SERVICEDESKADMIN_METADATA_FAILURE: 'FETCH_SERVICEDESKADMIN_METADATA_FAILURE',

  FETCH_SERVICEDESKADMIN_SEARCH_START: 'FETCH_SERVICEDESKADMIN_SEARCH_START',
  FETCH_SERVICEDESKADMIN_SEARCH_SUCCESS: 'FETCH_SERVICEDESKADMIN_SEARCH_SUCCESS',
  FETCH_SERVICEDESKADMIN_SEARCH_FAILURE: 'FETCH_SERVICEDESKADMIN_SEARCH_FAILURE',

  SERVICEDESKADMIN_PAGESIZE: 'SERVICEDESKADMIN_PAGESIZE',
  SERVICEDESKADMIN_PAGE_NUMBER: 'SERVICEDESKADMIN_PAGE_NUMBER',

  SHOW_BIG_LOADER: 'SHOW_BIG_LOADER',

  FETCH_IS_GOING_FORWARD_FLAG: 'FETCH_IS_GOING_FORWARD_FLAG',
  UPDATE_IS_GOING_FORWARD_FLAG: 'UPDATE_IS_GOING_FORWARD_FLAG',
  FETCH_PAGINARION_KEYS: 'FETCH_PAGINARION_KEYS',
  UPDATE_PAGINATION_KEYS: 'UPDATE_PAGINATION_KEYS',

  FETCH_SERVICE_DESK_ADMIN_SORT_START: 'FETCH_SERVICE_DESK_ADMIN_SORT_START',
  FETCH_SERVICE_DESK_ADMIN_SORT_SUCCESS: 'FETCH_SERVICE_DESK_ADMIN_SORT_SUCCESS',
  FETCH_SERVICE_DESK_ADMIN_SORT_FAILURE: 'FETCH_SERVICE_DESK_ADMIN_SORT_FAILURE',
  UPDATE_SERVICE_DESK_ADMIN_SORT_INFO: 'UPDATE_SERVICE_DESK_ADMIN_SORT_INFO',

  FETCH_SERVICEDESKADMIN_ITEMS_BY_USER_START: 'FETCH_SERVICEDESKADMIN_ITEMS_BY_USER_START',
  FETCH_SERVICEDESKADMIN_SORT_BY_USER_START: 'FETCH_SERVICEDESKADMIN_SORT_BY_USER_START',
  FETCH_SERVICEDESKADMIN_SEARCH_BY_USER_START: 'FETCH_SERVICEDESKADMIN_SEARCH_BY_USER_START'
}
export default ServiceDeskAdminActionTypes
